<a href="https://colab.research.google.com/github/Datriks/Pandas_Data_analysis/blob/master/Label_based_indexing_and_Slicing_with_loc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
summer = pd.read_csv('summer.csv',index_col = 'Athlete')
summer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31165 entries, HAJOS, Alfred to LIDBERG, Jimmy
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        31165 non-null  int64
 1   City        31165 non-null  object
 2   Sport       31165 non-null  object
 3   Discipline  31165 non-null  object
 4   Country     31161 non-null  object
 5   Gender      31165 non-null  object
 6   Event       31165 non-null  object
 7   Medal       31165 non-null  object
dtypes: int64(1), object(7)
memory usage: 2.1+ MB

In [ ]:
summer.head()

                    Year    City  ...                       Event   Medal
Athlete                           ...
HAJOS, Alfred       1896  Athens  ...              100M Freestyle    Gold
HERSCHMANN, Otto    1896  Athens  ...              100M Freestyle  Silver
DRIVAS, Dimitrios   1896  Athens  ...  100M Freestyle For Sailors  Bronze
MALOKINIS, Ioannis  1896  Athens  ...  100M Freestyle For Sailors    Gold
CHASAPIS, Spiridon  1896  Athens  ...  100M Freestyle For Sailors  Silver

[5 rows x 8 columns]

In [ ]:
summer.iloc[2]

Year                                1896
City                              Athens
Sport                           Aquatics
Discipline                      Swimming
Country                              GRE
Gender                               Men
Event         100M Freestyle For Sailors
Medal                             Bronze
Name: DRIVAS, Dimitrios, dtype: object

In [ ]:
summer.loc['DRIVAS, Dimitrios']

Year                                1896
City                              Athens
Sport                           Aquatics
Discipline                      Swimming
Country                              GRE
Gender                               Men
Event         100M Freestyle For Sailors
Medal                             Bronze
Name: DRIVAS, Dimitrios, dtype: object

In [ ]:
summer.loc['PHELPS, Michael']

                 Year     City     Sport  ... Gender                   Event   Medal
Athlete                                   ...
PHELPS, Michael  2004   Athens  Aquatics  ...    Men          100M Butterfly    Gold
PHELPS, Michael  2004   Athens  Aquatics  ...    Men          200M Butterfly    Gold
PHELPS, Michael  2004   Athens  Aquatics  ...    Men          200M Freestyle  Bronze
PHELPS, Michael  2004   Athens  Aquatics  ...    Men  200M Individual Medley    Gold
PHELPS, Michael  2004   Athens  Aquatics  ...    Men  400M Individual Medley    Gold
PHELPS, Michael  2004   Athens  Aquatics  ...    Men  4X100M Freestyle Relay  Bronze
PHELPS, Michael  2004   Athens  Aquatics  ...    Men     4X100M Medley Relay    Gold
PHELPS, Michael  2004   Athens  Aquatics  ...    Men  4X200M Freestyle Relay    Gold
PHELPS, Michael  2008  Beijing  Aquatics  ...    Men          100M Butterfly    Gold
PHELPS, Michael  2008  Beijing  Aquatics  ...    Men          200M Butterfly    Gold
PHELPS, Michael  2008  Beijing  Aquatics  ...    Men          200M Freestyle    Gold
PHELPS, Michael  2008  Beijing  Aquatics  ...    Men  200M Individual Medley    Gold
PHELPS, Michael  2008  Beijing  Aquatics  ...    Men  400M Individual Medley    Gold
PHELPS, Michael  2008  Beijing  Aquatics  ...    Men  4X100M Freestyle Relay    Gold
PHELPS, Michael  2008  Beijing  Aquatics  ...    Men     4X100M Medley Relay    Gold
PHELPS, Michael  2008  Beijing  Aquatics  ...    Men  4X200M Freestyle Relay    Gold
PHELPS, Michael  2012   London  Aquatics  ...    Men          100M Butterfly    Gold
PHELPS, Michael  2012   London  Aquatics  ...    Men          200M Butterfly  Silver
PHELPS, Michael  2012   London  Aquatics  ...    Men             200M Medley    Gold
PHELPS, Michael  2012   London  Aquatics  ...    Men        4X100M Freestyle  Silver
PHELPS, Michael  2012   London  Aquatics  ...    Men           4X100M Medley    Gold
PHELPS, Michael  2012   London  Aquatics  ...    Men        4X200M Freestyle    Gold

[22 rows x 8 columns]

### Indexing and Slicing Rows and Columns with loc[]

In [ ]:
summer.loc['PHELPS, Michael', 'Medal']

Athlete
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael    Bronze
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael    Bronze
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael      Gold
PHELPS, Michael    Silver
PHELPS, Michael      Gold
PHELPS, Michael    Silver
PHELPS, Michael      Gold
PHELPS, Michael      Gold
Name: Medal, dtype: object

In [ ]:
summer.loc['PHELPS, Michael', ['Medal','Event']]

                  Medal                   Event
Athlete
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael  Bronze          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael  Bronze  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael    Gold          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael    Gold  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael  Silver          200M Butterfly
PHELPS, Michael    Gold             200M Medley
PHELPS, Michael  Silver        4X100M Freestyle
PHELPS, Michael    Gold           4X100M Medley
PHELPS, Michael    Gold        4X200M Freestyle

In [ ]:
summer.loc[['PHELPS, Michael','LEWIS, Carl'], ['Medal','Event']]

                  Medal                   Event
Athlete
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael  Bronze          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael  Bronze  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael    Gold          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael    Gold  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael  Silver          200M Butterfly
PHELPS, Michael    Gold             200M Medley
PHELPS, Michael  Silver        4X100M Freestyle
PHELPS, Michael    Gold           4X100M Medley
PHELPS, Michael    Gold        4X200M Freestyle
LEWIS, Carl        Gold                    100M
LEWIS, Carl        Gold                    200M
LEWIS, Carl        Gold            4X100M Relay
LEWIS, Carl        Gold               Long Jump
LEWIS, Carl        Gold                    100M
LEWIS, Carl      Silver                    200M
LEWIS, Carl        Gold               Long Jump
LEWIS, Carl        Gold            4X100M Relay
LEWIS, Carl        Gold               Long Jump
LEWIS, Carl        Gold               Long Jump

In [ ]:
summer.loc[:,['Medal','Event']]

                            Medal                       Event
Athlete
HAJOS, Alfred                Gold              100M Freestyle
HERSCHMANN, Otto           Silver              100M Freestyle
DRIVAS, Dimitrios          Bronze  100M Freestyle For Sailors
MALOKINIS, Ioannis           Gold  100M Freestyle For Sailors
CHASAPIS, Spiridon         Silver  100M Freestyle For Sailors
...                           ...                         ...
JANIKOWSKI, Damian         Bronze                    Wg 84 KG
REZAEI, Ghasem Gholamreza    Gold                    Wg 96 KG
TOTROV, Rustam             Silver                    Wg 96 KG
ALEKSANYAN, Artur          Bronze                    Wg 96 KG
LIDBERG, Jimmy             Bronze                    Wg 96 KG

[31165 rows x 2 columns]

In [ ]:
summer.head(10)

                       Year    City  ...                       Event   Medal
Athlete                              ...
HAJOS, Alfred          1896  Athens  ...              100M Freestyle    Gold
HERSCHMANN, Otto       1896  Athens  ...              100M Freestyle  Silver
DRIVAS, Dimitrios      1896  Athens  ...  100M Freestyle For Sailors  Bronze
MALOKINIS, Ioannis     1896  Athens  ...  100M Freestyle For Sailors    Gold
CHASAPIS, Spiridon     1896  Athens  ...  100M Freestyle For Sailors  Silver
CHOROPHAS, Efstathios  1896  Athens  ...             1200M Freestyle  Bronze
HAJOS, Alfred          1896  Athens  ...             1200M Freestyle    Gold
ANDREOU, Joannis       1896  Athens  ...             1200M Freestyle  Silver
CHOROPHAS, Efstathios  1896  Athens  ...              400M Freestyle  Bronze
NEUMANN, Paul          1896  Athens  ...              400M Freestyle    Gold

[10 rows x 8 columns]

In [ ]:
summer.loc[:'CHASAPIS, Spiridon']

                    Year    City  ...                       Event   Medal
Athlete                           ...
HAJOS, Alfred       1896  Athens  ...              100M Freestyle    Gold
HERSCHMANN, Otto    1896  Athens  ...              100M Freestyle  Silver
DRIVAS, Dimitrios   1896  Athens  ...  100M Freestyle For Sailors  Bronze
MALOKINIS, Ioannis  1896  Athens  ...  100M Freestyle For Sailors    Gold
CHASAPIS, Spiridon  1896  Athens  ...  100M Freestyle For Sailors  Silver

[5 rows x 8 columns]

In [ ]:
# multiple ocurences of phelps, pandas does not know from where to slice
summer.loc[:,'PHELPS, Michael']

KeyError: ignored

In [ ]:
summer.head(10)

                       Year    City  ...                       Event   Medal
Athlete                              ...
HAJOS, Alfred          1896  Athens  ...              100M Freestyle    Gold
HERSCHMANN, Otto       1896  Athens  ...              100M Freestyle  Silver
DRIVAS, Dimitrios      1896  Athens  ...  100M Freestyle For Sailors  Bronze
MALOKINIS, Ioannis     1896  Athens  ...  100M Freestyle For Sailors    Gold
CHASAPIS, Spiridon     1896  Athens  ...  100M Freestyle For Sailors  Silver
CHOROPHAS, Efstathios  1896  Athens  ...             1200M Freestyle  Bronze
HAJOS, Alfred          1896  Athens  ...             1200M Freestyle    Gold
ANDREOU, Joannis       1896  Athens  ...             1200M Freestyle  Silver
CHOROPHAS, Efstathios  1896  Athens  ...              400M Freestyle  Bronze
NEUMANN, Paul          1896  Athens  ...              400M Freestyle    Gold

[10 rows x 8 columns]

In [ ]:
summer.loc['DRIVAS, Dimitrios':'BLAKE, Arthur']

                       Year    City  ...                       Event   Medal
Athlete                              ...
DRIVAS, Dimitrios      1896  Athens  ...  100M Freestyle For Sailors  Bronze
MALOKINIS, Ioannis     1896  Athens  ...  100M Freestyle For Sailors    Gold
CHASAPIS, Spiridon     1896  Athens  ...  100M Freestyle For Sailors  Silver
CHOROPHAS, Efstathios  1896  Athens  ...             1200M Freestyle  Bronze
HAJOS, Alfred          1896  Athens  ...             1200M Freestyle    Gold
ANDREOU, Joannis       1896  Athens  ...             1200M Freestyle  Silver
CHOROPHAS, Efstathios  1896  Athens  ...              400M Freestyle  Bronze
NEUMANN, Paul          1896  Athens  ...              400M Freestyle    Gold
PEPANOS, Antonios      1896  Athens  ...              400M Freestyle  Silver
LANE, Francis          1896  Athens  ...                        100M  Bronze
SZOKOLYI, Alajos       1896  Athens  ...                        100M  Bronze
BURKE, Thomas          1896  Athens  ...                        100M    Gold
HOFMANN, Fritz         1896  Athens  ...                        100M  Silver
CURTIS, Thomas         1896  Athens  ...                110M Hurdles    Gold
GOULDING, Grantley     1896  Athens  ...                110M Hurdles  Silver
LERMUSIAUX, Albin      1896  Athens  ...                       1500M  Bronze
FLACK, Edwin           1896  Athens  ...                       1500M    Gold
BLAKE, Arthur          1896  Athens  ...                       1500M  Silver

[18 rows x 8 columns]

In [ ]:
summer.loc['DRIVAS, Dimitrios':'BLAKE, Arthur','City':'Discipline']

                         City      Sport Discipline
Athlete
DRIVAS, Dimitrios      Athens   Aquatics   Swimming
MALOKINIS, Ioannis     Athens   Aquatics   Swimming
CHASAPIS, Spiridon     Athens   Aquatics   Swimming
CHOROPHAS, Efstathios  Athens   Aquatics   Swimming
HAJOS, Alfred          Athens   Aquatics   Swimming
ANDREOU, Joannis       Athens   Aquatics   Swimming
CHOROPHAS, Efstathios  Athens   Aquatics   Swimming
NEUMANN, Paul          Athens   Aquatics   Swimming
PEPANOS, Antonios      Athens   Aquatics   Swimming
LANE, Francis          Athens  Athletics  Athletics
SZOKOLYI, Alajos       Athens  Athletics  Athletics
BURKE, Thomas          Athens  Athletics  Athletics
HOFMANN, Fritz         Athens  Athletics  Athletics
CURTIS, Thomas         Athens  Athletics  Athletics
GOULDING, Grantley     Athens  Athletics  Athletics
LERMUSIAUX, Albin      Athens  Athletics  Athletics
FLACK, Edwin           Athens  Athletics  Athletics
BLAKE, Arthur          Athens  Athletics  Athletics

In [ ]:
summer.loc['PHELPS, Michael']